POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "123123123"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "VS Code Failman"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "fieldNotRequired": "VS Code Failman"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json